---
project: deblur_gan
experiment_desc: fpn

train:
  files_a: /home/jili_cw4/dd_dp_dataset_canon_patch/train_c/source/*.png #/home/jili/yangziyi/data_to_liji/Defocus_Train/Blurred/*.png  #/home/jili/GOPRO_Large/train/**/blur/*.png # /home/jili/GOPRO_Large/train/GOPR0372*/blur/*.png # /home/jili/ground_truth/train/blur/*01.png #/home/jili/GOPRO_Large/train/**/blur/*.png #&FILES_A /datasets/my_dataset/**/*.jpg
  files_b: /home/jili_cw4/dd_dp_dataset_canon_patch/train_c/target/*.png #/home/jili/yangziyi/data_to_liji/Defocus_Train/GT/*.png  #/home/jili/GOPRO_Large/train/**/sharp/*.png #/home/jili/GOPRO_Large/train/GOPR0372*/sharp/*.png #/home/jili/ground_truth/train/sharp/*01.png #/home/jili/GOPRO_Large/train/**/sharp/*.png #*FILES_A
  size: &SIZE 256 #256
  crop: random
  preload: &PRELOAD false
  preload_size: &PRELOAD_SIZE 0
  bounds: [0,1] #[0, .9]
  scope: geometric
#  corrupt: &CORRUPT
#    - name: cutout
#      prob: 0.5
#      num_holes: 3
#      max_h_size: 25
#      max_w_size: 25
#    - name: jpeg
#      quality_lower: 70
#      quality_upper: 90
#    - name: motion_blur
#    - name: median_blur
#    - name: gamma
#    - name: rgb_shift
#    - name: hsv_shift
#    - name: sharpen

val:
  files_a: /home/jili_cw4/dd_dp_dataset_canon_patch/train_c/source/*.png #/home/jili/yangziyi/data_to_liji/Defocus_Test/Blurred/*.png #/home/jili/GOPRO_Large/test/**/blur/*.png #/home/jili/GOPRO_Large/train/GOPR0386*/blur/*.png # /home/jili/ground_truth/test/blur/*01.png #/home/jili/GOPRO_Large/test/**/blur/*.png #*FILES_A
  files_b: /home/jili_cw4/dd_dp_dataset_canon_patch/train_c/target/*.png #/home/jili/yangziyi/data_to_liji/Defocus_Test/GT/*.png #/home/jili/GOPRO_Large/test/**/sharp/*.png #*FILES_A/home/jili/GOPRO_Large/train/GOPR0386*/sharp/*.png #/home/jili/ground_truth/test/sharp/*01.png #/home/jili/GOPRO_Large/test/**/sharp/*.png #*FILES_A
  size: *SIZE
  scope: geometric
  crop: center
  preload: *PRELOAD
  preload_size: *PRELOAD_SIZE
  bounds: [.9,1] #[.9, 1]
#  corrupt: *CORRUPT

phase: train
warmup_num: 3
model:
  g_name: fpn_inception
  blocks: 9
  d_name: double_gan # may be no_gan, patch_gan, double_gan, multi_scale
  d_layers: 3
  content_loss: perceptual
  adv_lambda: 0.001
  disc_loss: wgan-gp
  learn_residual: True
  norm_layer: instance
  dropout: True

num_epochs: 500
train_batches_per_epoch: 1000 #1000
val_batches_per_epoch: 100 #100
batch_size: 8 #1
image_size: [256, 256]

optimizer:
  name: adam
  lr: 0.0001
scheduler:
  name: linear
  start_epoch: 50
  min_lr: 0.0000001

